### ISSUE TITLE
This doesn't work based on .ENV variables

### ISSUE THREAD

**Issue by shabaz-ejaz** [imanghafoori1/laravel-anypass#3]
I have just installed and tested this package.

I have the following in my .ENV:
```
APP_ENV=local
APP_DEBUG=true
ANY_PASS=true
```

I then changed the `config/auth.php` so that it uses anyPass as you showed in this [issue](https://github.com/imanghafoori1/laravel-anypass/issues/1):

```
'providers' => [
        'users' => [
            'driver' => 'eloquentAnyPass',
            'model' => App\Models\User::class,
        ]
    ],

```

So now I can log in with any password which is fine.

However if I change `ANY_PASS=false` or `APP_DEBUG=false` and then clear my config cache it still allows me to log in with any password. There is no checking to see if we are on a local environment which is a very dangerous move.

Testing on Laravel 5.6 on PHP 7.2.5

**Comment by imanghafoori1** [comment]
Hi
If you are using `php artisan serve` to spin up a web server.
You have to restart it after changing the .env variables.

**Comment by shabaz-ejaz** [comment]
No I have tested on a live server to see how it performs. It doesn't take into account any of the .env variables it just allows me to log in with any password.

**Comment by imanghafoori1** [comment]
It seems your env variables are cached and are not updated with the new values yet.
You may put ```dd(env('APP_ENV'), env('ANY_PASS'), env('APP_DEBUG'))``` in your web.php file and check the values.
Also make sure you have installed the latest version of the package

**Comment by shabaz-ejaz** [comment]
Nope. I cleared all config cache as you normally would. I can confirm this by doing `php artisan tinker` and typing `env('ANY_PASS')` and it returns false which is fine. 

So the env variables are being picked up perfectly fine.

The version is set to `"imanghafoori/laravel-anypass": "^1.0",` as I followed your instructions on your readme page to do this: `composer require --dev imanghafoori/laravel-anypass`

**Comment by imanghafoori1** [comment]
Do not use tinker.
put
`dd(env('APP_ENV'), env('ANY_PASS'), env('APP_DEBUG'));`

in your web.php file and check the values.

**Comment by imanghafoori1** [comment]
Any way, you may want to take a quick look at the AnyPassServiceProvider.php file.
each and every env variable is checked there.

```php

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        \Auth::provider('eloquentAnyPass', function ($app, array $config) {
            return new AnyPassEloquentUserProvider($app['hash'], $config["model"]);
        });

        \Auth::provider('databaseAnyPass', function ($app, array $config) {
            $connection = $app['db']->connection();

            return new AnyPassDatabaseUserProvider($connection, $app['hash'], $config['table']);
        });

        if (dd($this->properConfig(), env('ANY_PASS', false) )) {
            $this->changeUsersDriver();
        }
    }

    /**
     * @return bool
     */
    private function properConfig()
    {
        return env('APP_DEBUG') === true && $this->appEnvIsSafe() && env('ANY_PASS', false) === true;
    }

    private function changeUsersDriver()
    {
        $driver = config()->get('auth.providers.users.driver');
        if (in_array($driver, ['eloquent', 'database',])) {
            config()->set('auth.providers.users.driver', $driver.'AnyPass');
        }
    }

    /**
     * @return bool
     */
    private function appEnvIsSafe()
    {
        return in_array(env('APP_ENV'), ['local', 'testing']);
    }

```

**Comment by imanghafoori1** [comment]
I did not found any problems with my own setup.
Check the AnyPassServiceProvider.php file.
env variables are checked there.
 if you have the latest version. It should look like this:

```php
    public function register()
    {
        \Auth::provider('eloquentAnyPass', function ($app, array $config) {
            return new AnyPassEloquentUserProvider($app['hash'], $config["model"]);
        });

        \Auth::provider('databaseAnyPass', function ($app, array $config) {
            $connection = $app['db']->connection();

            return new AnyPassDatabaseUserProvider($connection, $app['hash'], $config['table']);
        });

        if ($this->properConfig()) {
            $this->changeUsersDriver();
        }
    }

    /**
     * @return bool
     */
    private function properConfig()
    {
        return env('APP_DEBUG') === true && $this->appEnvIsSafe() && env('ANY_PASS', false) === true;
    }

    private function changeUsersDriver()
    {
        $driver = config()->get('auth.providers.users.driver');
        if (in_array($driver, ['eloquent', 'database',])) {
            config()->set('auth.providers.users.driver', $driver.'AnyPass');
        }
    }

    /**
     * @return bool
     */
    private function appEnvIsSafe()
    {
        return in_array(env('APP_ENV'), ['local', 'testing']);
    }

**Comment by imanghafoori1** [comment]
oh yes,
I got your problem now
in the new version you should NOT ` 'driver' => 'eloquentAnyPass',` ( it was for the old version)
instead you should have `   'driver' => 'eloquent',`

```php
'providers' => [
        'users' => [
            'driver' => 'eloquentAnyPass', //(incorrect)
            'model' => App\Models\User::class,
        ]
    ],```

**Comment by shabaz-ejaz** [comment]
Okay, it seems to work now due to the `eloquent` driver. I think its important to document this clearly in the readme file as anyone who is on the latest version of Laravel may stumble across this issue.

Thanks

**Comment by imanghafoori1** [comment]
I think very few people have installed the old version.
I also deleted the miss leading picture in the issue you mention.

Good luck with it.
